# https://travis-ci.org/#!/phlax/aioworker
dist: trusty
language: python
python:
  - "3.5"

install:
  - pip install cython
  - pip install -e .
  - pip install aioworker[test]
  - python3 setup.py build_ext --inplace

script:
  - flake8 .
  - pytest -vv
