/* Generated by Cython 0.29.5 */

#ifndef __PYX_HAVE__aioworker__worker
#define __PYX_HAVE__aioworker__worker


#ifndef __PYX_HAVE_API__aioworker__worker

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *__pyx_f_9aioworker_6worker_get_worker(int __pyx_skip_dispatch);

#endif /* !__PYX_HAVE_API__aioworker__worker */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initworker(void);
#else
PyMODINIT_FUNC PyInit_worker(void);
#endif

#endif /* !__PYX_HAVE__aioworker__worker */
